import Head from 'next/head'
import Image from 'next/image'


import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NFT Minting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="row">
          <form class="col-lg-5 mt-5" style={{ borderRadius: "25px", boxShadow: "1px 1px 10px #ffd700" }}>
            <h4>Mint Central</h4>
            <h5>Please connect your wallet</h5>

            <Button style={{ marginBottom: "5px" }}>Connect Wallet</Button>

            <div class="card" id="wallet-address" style={{ marginTop: "3px" }}>
              <label for="floatingInput">Wallet Address</label>
              <input type="number" name="amount" defaultValue="1" min="1" max="5" />
              <label className="">Please select the amount the NFTs to mint</label>
              <Button>Mint/Buy</Button>
            </div>
            <label>Price 0.06 ETH each mint</label>
          </form>
        </div>
      </div>

    </div>
  )
}
